default_language_version:
  python: python3.8
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        language: system
        entry: black
        args: ["--check"]
        types: [python]
      - id: isort
        name: isort
        language: system
        entry: isort
        args: ["--check", "--diff", "--color"]
        types: [python]
      - id: flake8
        name: flake8
        language: system
        entry: flake8
        types: [python]
        exclude: "migrations"

